---
title: "mammal"
author: "ddxbugs"
date: "2024-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
setwd("../brain")

library(plotly)
library(ggplot2)
library(tidyverse)

```

```{r}
df <- read.csv("Brain.csv", header=TRUE)
df
```

```{r}
# install.packages("naniar")
library(naniar)
gg_miss_var(df)
```
# Plot the data
```{r}
plot(df)
```
# Perform log-log transformation
```{r}
logBrain <- log(df$Brain)
logGestation <- log(df$Gestation)
logLitter <- log(df$Litter)
logBody <- log(df$Body)
logDF <- data.frame(Species=df$Species, LogBrain=logBrain, LogGestation=logGestation, LogLitter=logLitter, LogBody=logBody)
logDF
```
# Plot the log-log transformation
```{r}
plot(logDF)
```

```{r}
fit <- lm(Brain ~ Gestation + Litter + Body, data=df)
summary(fit)
anova(fit)
```
```{r}
plot(fit)
```



```{r}
logFit <- lm(logBrain ~ logGestation + logLitter + logBody, data=logDF)
summary(logFit)
anova(logFit)
```

```{r}
logFit %>% ggplot(aes(logGestation, logLitter, color=logBody)) + geom_point() + geom_smooth(method="lm") + ggtitle("Linear regression model: log(Brain)~log(Gestation)+log(Litter)")
#dataset %>% ggplot(aes(Force, Height, color=Species, shape=Species)) + geom_point() + ggtitle("Scatter plot: ") 
plot(logFit)
```
# Scatter plot of residuals
```{r}
plot(logFit$residuals, main="Scatter plot of residuals",
     xlab="Predicted values", ylab="Residuals", pch=19)
abline(h=0, col="black")
```
# Histogram of residuals with normal distribution
```{r}
resids <- logFit$residuals
x_bar <- mean(resids)
std_dev <- var(resids)

hist(resids, density=20, breaks=20, prob=TRUE, col="red",
     xlab="Residuals", ylim=c(0,2),
     main="Histogram of residuals ~ N(0,1)")
curve(dnorm(x, mean=x_bar, sd=std_dev),
      col="darkblue", lwd=2, add=TRUE, yaxt="n")
```
# Q-Q plot
```{r}
library(car)
qqPlot(logFit$residuals, xlab="Quantiles", ylab="Residuals", main="Q-Q plot of residuals")
```
# Studentized residual plot
```{r}
library(MASS)

# calculate studentized residuals
sresids <- studres(logFit)
plot(logFit$fitted.values, sresids, ylab="Studentized residuals", xlab="Predicted values", main="Studentized residuals Plot")
abline(h=c(-2,2), v=0, col="darkblue")
```

# Calculate the MSE
```{r}
resids <- resid(logFit)
MSE <- sum(resids^2) / length(resids)
MSE
```
# Calculate 95% confidence interval
```{r}
# Coefficients from the regression output
coef_logGestation <- 0.41794
coef_logLitter <- -0.31007

# Standard errors from the regression output
se_logGestation <- 0.14078
se_logLitter <- 0.11593

# Calculate the confidence intervals
ci_logGestation <- exp(c(coef_logGestation - 1.984 * se_logGestation, coef_logGestation + 1.984 * se_logGestation))
ci_logLitter <- exp(c(coef_logLitter - 1.984 * se_logLitter, coef_logLitter + 1.984 * se_logLitter))

# Print the back-transformed confidence intervals
print(ci_logGestation)
print(ci_logLitter)
```






