---
title: "anova"
author: "ddxbugs"
date: "2024-02-26"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# install.packages("agricolae")
# install.packages("multcomp")
# install.packages("DescTools")
# install.packages("pairwiseCI")
library(emmeans)
library(agricolae)
library(ggplot2)
library(multcomp)
library(onewaytests)
library(car)
library(DescTools)
library(pairwiseCI)
library(tidyverse)
```
# Data import and preprocessing
```{r}
df <- read.csv("handicap.csv")

str(df)
df$Handicap <- factor(df$Handicap)
unique(df$Handicap)
```
# Exploratory Data Analysis
```{r}
df %>% group_by(Handicap) %>% summarise(xbar=mean(Score), s=sd(Score), n=n())

ggplot(df, aes(Score, fill=Handicap)) + geom_histogram(binwidth=1) + facet_grid(~Handicap) + labs(x="Score", y="Frequency", title="Histogram by Handicap")
ggplot(df, aes(Handicap, Score, shape=Handicap, color=Handicap)) + geom_point(position="jitter") + labs(x="Handicap", y="Score", title="Scatter plot by Handicap")
ggplot(df, aes(Handicap, Score, fill=Handicap)) + geom_boxplot() + labs(x="Handicap", y="Score", title="Boxplot by Handicap")
```
# Preliminary analysis of variance
```{r}
leveneTest(Score~Handicap, data=df)
bf.test(Score~Handicap, data=df)
```
# Multiple comparisons
```{r}
fit <- aov(Score~Handicap, data=df)
summary(fit)

# Contrasts
leastsquare <- lsmeans(fit, "Handicap")
contrasts <- list(constrast <- c(0.5, -0.5, 0.5, 0, -0.5))
contrast(leastsquare, contrasts, adjust="sidak")
contrast(leastsquare, contrasts)
```

# Post-hoc ANOVA
```{r}

df.bon <- LSD.test(fit, 'Handicap', p.adj='bonferroni')
df.lsd <- LSD.test(fit, 'Handicap', p.adj='none')
df.scheffe <- scheffe.test(fit, 'Handicap')
df.tukey <- HSD.test(fit, 'Handicap')
df.dunnett <- DunnettTest(df$Score, df$Handicap, control='None')


df.bon
df.lsd
df.scheffe
df.tukey
df.dunnett

# Bonferroni
summary(glht(fit, linfct=mcp(Handicap="Tukey")), test=adjusted(type="bonferroni"))
pairwiseCI(Score~Handicap, data=df)
pairwise.t.test(df$Score, df$Handicap, p.adjust="bonferroni")

# LSD
summary(glht(fit, linfct=mcp(Handicap="Tukey")), test=adjusted(type="none"))
confint(glht(fit, linfct=mcp(Handicap="Tukey")))

# Tukey-Kramer
summary(glht(fit, linfct=mcp(Handicap="Tukey")))
confint(glht(fit, linfct=mcp(Handicap="Tukey")))

# Scheffe
ScheffeTest(x=fit, data=df, which="Handicap")

# Dunnett Contrast
summary(glht(fit, linfct=mcp(Handicap="Dunnett")))
confint(glht(fit, linfct=mcp(Handicap="Dunnett")))
```

```{r}
percent_change <- function(x)  {
  return ((exp(x)-1)*100)
}
mean_diff <- c(0.50669, 0.67069, 0.99856, 0.40588, 0.56987, 0.89775, 0.16400, 0.49187, 0.32787)
education <- c('>16- 13-15', '>16 - 12', '>16 - <12', '16 - 13-15', '16 - 12', '16 - <12', 
               '13-15 - 12', '13-15 - <12', '12 - <12')
percent_diff <- percent_change(mean_diff)
df1 <- data.frame(education, percent_diff)
df1


```
