---
title: "wheatears"
author: "ddxbugs"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
sessionInfo()

# install.packages("investr")
library(investr)

df <- read.csv("../wheatears/Male Display Data Set.csv", header=TRUE)
str(df)
summary(df)
sum(is.na(df))

plot(df)
```

```{r}
fit <- lm(Tcell~Mass, data=df)
anova(fit)
summary(fit)
```

```{r}
predict(fit, interval="confidence", level=0.99)
```

```{r}
newpoint <- data.frame(Mass=4.5, Tcell=NA)
predict(fit, newdata=newpoint, interval="confidence", level=0.99)
```

```{r}
predict(fit, newdata=newpoint, interval="prediction", level=0.99)
```
```{r}
calibrate(fit, y0=0.3, level=0.99, interval="Wald", mean.response=TRUE, limit=FALSE)
```
```{r}
calibrate(fit, y0=0.3, level=0.99, interval="Wald", mean.response=FALSE, limit=FALSE)
```
```{r}
newx <- df$Mass
newx <- sort(newx)

pred_x <- predict(fit, newdata=data.frame(Mass=newx), interval="confidence", type="response", level=0.99)
pred_y <- predict(fit, newdata=data.frame(Mass=newx), interval="prediction", type="response", level=0.99)
```


```{r}
plot(df, xlim=c(3,10), ylim=c(-0.1,0.8), xlab="Mass(g)", ylab="Tcell", main="Fitted Plot: Tcell Response ~ Mass (grams)", cex=0.5)
abline(fit, col="red")
abline(h=0.3, col="blue")
text(x=3, y=0.28, "y0 = 0.3", col="blue", cex=.5)
lines(newx, pred_x[,2], col="black", lty=2, lwd=1)
lines(newx, pred_x[,3], col="black", lty=2, lwd=1)
lines(newx, pred_y[,2], col="green", lty=2, lwd=2)
lines(newx, pred_y[,3], col="green", lty=2, lwd=2)
```
```{r}
plot(fit$residuals, main="Residual Plot", xlab="Predicted Values", ylab="Residuals")
abline(h=0, col="black")
```
```{r}
x_resids <- mean(fit$residuals)
s_resids <- sqrt(var(fit$residuals))
hist(fit$residuals, density=20, breaks=20, prob=TRUE, col="red",
     xlab="Residuals", ylim=c(0,8),
     main="Histogram of Residuals ~ N(4.707618e-18,0.07896801)")
curve(dnorm(x, mean=x_resids, sd=s_resids), col="darkblue", lwd=2, add=TRUE, yaxt="n")
```





