---
title: "model"
author: "ddxbugs"
date: "2024-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sessionInfo()
getwd()
setwd("../crabs")
```


```{r}
dataset <- read.csv("Crab17.csv", header=TRUE)
dataset
```

# Plot the data
```{r}
library(tidyverse)

dataset %>% ggplot(aes(Height, Force, color=Species)) + geom_point() + geom_smooth(method="lm") + ggtitle("Linear regression model: crab species closing force v. propodus height")
dataset %>% ggplot(aes(Height,Force,  color=Species, shape=Species)) + geom_point() + ggtitle("Scatter plot: crab species closing force v. propodus height") 
```
# Build the model
```{r}
# force = b0 + b1*height + b2*species + b3(height*species)
model <- lm(Force~Height+Species+Height*Species, data=dataset)
summary(model)
anova(model)
```
# Residual plots
```{r}
plot(model)
```
# Scatter plot of residuals
```{r}
plot(model$residuals, main="Scatter plot of residuals", xlab="Predicted values", ylab="Residuals", pch=19)
abline(h=0, col="black")
```
# Histogram of residuals
```{r}
resid <- model$residuals
x_bar <- mean(resid)
std_dev <- sqrt(var(resid))
hist(resid, density=20, breaks=20, prob=TRUE, col="red",
     xlab="Residuals", ylim=c(0,0.2),
     main="Histogram of residuals ~ N(0,1)")
curve(dnorm(x, mean=x_bar, sd=std_dev),
      col="darkblue", lwd=2, add=TRUE, yaxt="n")
```
# Q-Q residual plot
```{r}
# install.packages("car")
library(car)
qqPlot(model$residuals, xlab="Quantile", ylab="Residuals", main="Q-Q plot of residuals")
```
# Studentized residual plot
```{r}
library(MASS)
# calculate the studentized residuals
sresids <- studres(model)
plot(model$fitted.values, sresids, ylab="Studentized residuals", xlab="Predicted values", main="Studentized residuals plot")
abline(h=0)
```







